events { worker_connections 1024; }

http {
  server {
    listen 80;
    server_name app.somosdex.com;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location / {
      return 200 "OK - aguardando SSL";
      add_header Content-Type text/plain;
    }
  }
}
